version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hyve-postgres
    restart: always
    environment:
      POSTGRES_USER: hyve
      POSTGRES_PASSWORD: hyvepass
      POSTGRES_DB: hyve
    ports:
      - "5433:5432"
    volumes:
      - hyve-pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  celery-worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hyve-celery-worker
    command: celery -A worker.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    restart: always

volumes:
  hyve-pgdata:
